---
title: "quantum-visualization"
author: "Robert Jankowski"
date: "11/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gridExtra)
library(scales)
library(latex2exp)
```

***
## Testowanie poprawności algorytmu przy wyłączonym polu oscylującym (kappa = 0, omage = 0) dla n=1,4,9
```{r}
## Plik konfiguracyjny, tylko n się zmieniało
# 100   # N
# 10    # tau
# 1e-4  # delta_tau
# 0     # kappa
# 0     # omega
# 9     # n
# 1000  # save_metrics
# 1000  # save_density
```


```{r, info=F, warning=F, message=F}
metrics_n1 <- read_csv("../output/metrics_init_n=1.csv", col_names = F)
metrics_n4 <- read_csv("../output/metrics_init_n=4.csv", col_names = F)
metrics_n9 <- read_csv("../output/metrics_init_n=9.csv", col_names = F)

colnames(metrics_n1) <- c("tau", "N", "<x>", "epsilon")
colnames(metrics_n4) <- c("tau", "N", "<x>", "epsilon")
colnames(metrics_n9) <- c("tau", "N", "<x>", "epsilon")
```

**Norma**
```{r, fig.width=10, fig.height=5}
norm <- ggplot() +
  geom_line(data = metrics_n1, aes(tau, N, color = "n=1")) +
  geom_line(data = metrics_n4, aes(tau, N, color = "n=4")) +
  geom_line(data = metrics_n9, aes(tau, N, color = "n=9")) +
  labs(y = "N", x = TeX("$\\tau$")) + 
  theme_light() +
  theme(legend.position = "top", 
        legend.title = element_blank(), legend.text = element_text(size = 13), 
        text = element_text(size = 14))

# ggsave(filename="plots/norm_n_1_4_9.pdf", plot = norm, width = 6, height = 4, units = "in")
norm
```

**<x>**
```{r, fig.width=10, fig.height=5}
xmean <- ggplot() +
  geom_line(data = metrics_n1, aes(tau, `<x>`, color = "n=1")) +
  geom_line(data = metrics_n4, aes(tau, `<x>`, color = "n=4")) +
  geom_line(data = metrics_n9, aes(tau, `<x>`, color = "n=9")) +
  labs(y = TeX("$<x>$"), x = TeX("$\\tau$")) +
  theme_light() +
    theme(legend.position = "top", 
        legend.title = element_blank(), legend.text = element_text(size = 13), 
        text = element_text(size = 14))
xmean
# ggsave(filename="plots/xmean_n_1_4_9.pdf", plot = xmean, width = 6, height = 4, units = "in")
```
**Energia**
```{r, fig.width=10, fig.height=5}
energy <- ggplot() +
  geom_line(data = metrics_n1, aes(tau, epsilon, color = "n=1")) +
  geom_line(data = metrics_n4, aes(tau, epsilon, color = "n=4")) +
  geom_line(data = metrics_n9, aes(tau, epsilon, color = "n=9")) +
  theme_light() +
  labs(y = TeX("$\\epsilon$"), x = TeX("$\\tau$")) +
      theme(legend.position = "top", 
        legend.title = element_blank(), legend.text = element_text(size = 13), 
        text = element_text(size = 14))
# ggsave(filename="plots/energy_n_1_4_9.pdf", plot = energy, width = 6, height = 4, units = "in")
energy
```

# Symulacje z zaburzającym się polem elektrycznym
```{r}
## Plik konfiguracyjny
# 100   # N
# 5     # tau
# 1e-4  # delta_tau
# 8     # kappa
# 0     # omega
# 4     # n
# 1000  # save_metrics
# 1000  # save_density
```


```{r, info=F, warning=F, message=F}
metrics_omega15 <- read_csv("../output/resonance_metrics_kappa=3__omega=15_n=1.csv", col_names = F)
metrics_omega10 <- read_csv("../output/resonance_metrics_kappa=3__omega=10_n=1.csv", col_names = F)
metrics_omega20 <- read_csv("../output/resonance_metrics_kappa=3__omega=20_n=1.csv", col_names = F)

colnames(metrics_omega15) <- c("tau", "N", "<x>", "epsilon")
colnames(metrics_omega10) <- c("tau", "N", "<x>", "epsilon")
colnames(metrics_omega20) <- c("tau", "N", "<x>", "epsilon")
```

**Energia**
```{r, fig.width=12, fig.height=5}
# n = 1
ggplot() +
  geom_line(data = metrics_omega10, aes(tau, epsilon, color = "omega=10")) +
  geom_line(data = metrics_omega15, aes(tau, epsilon, color = "omega=15")) +
  geom_line(data = metrics_omega20, aes(tau, epsilon, color = "omega=20")) +
  theme_light() +
  labs(y = TeX("$\\epsilon$"), x = TeX("$\\tau$")) +
  scale_color_discrete(labels = unname(TeX(c("$\\omega = 10$", "$\\omega = 15$", "$\\omega = 20$")))) +
  theme(legend.position = "top", 
        legend.title = element_blank(), legend.text = element_text(size = 13), 
        text = element_text(size = 14))
```

```{r, info=F, warning=F, message=F}
# n = 4
metrics_omega33 <- read_csv("../output/resonance_metrics_kappa=3__omega=33_n=4.csv", col_names = F)
metrics_omega34 <- read_csv("../output/resonance_metrics_kappa=3__omega=34_n=4.csv", col_names = F)
metrics_omega35 <- read_csv("../output/resonance_metrics_kappa=3__omega=35_n=4.csv", col_names = F)

colnames(metrics_omega33) <- c("tau", "N", "<x>", "epsilon")
colnames(metrics_omega34) <- c("tau", "N", "<x>", "epsilon")
colnames(metrics_omega35) <- c("tau", "N", "<x>", "epsilon")
```

```{r, fig.width=12, fig.height=5}
# n = 4
ggplot() +
  geom_line(data = metrics_omega33, aes(tau, epsilon, color = "omega=33")) +
  geom_line(data = metrics_omega34, aes(tau, epsilon, color = "omega=34")) +
  geom_line(data = metrics_omega35, aes(tau, epsilon, color = "omega=35")) +
  theme_light() +
  labs(y = TeX("$\\epsilon$"), x = TeX("$\\tau$")) +
  scale_color_discrete(labels = unname(TeX(c("$\\omega = 33$", "$\\omega = 34$", "$\\omega = 35$")))) +
  theme(legend.position = "top", 
        legend.title = element_blank(), legend.text = element_text(size = 13), 
        text = element_text(size = 14))
```
```{r, info=F, warning=F, message=F}
# n = 9
metrics_omega91 <- read_csv("../output/resonance_metrics_kappa=3__omega=91_n=9.csv", col_names = F)
metrics_omega92 <- read_csv("../output/resonance_metrics_kappa=3__omega=92_n=9.csv", col_names = F)
metrics_omega93 <- read_csv("../output/resonance_metrics_kappa=3__omega=93_n=9.csv", col_names = F)
metrics_omega94 <- read_csv("../output/resonance_metrics_kappa=3__omega=94_n=9.csv", col_names = F)
metrics_omega95 <- read_csv("../output/resonance_metrics_kappa=3__omega=95_n=9.csv", col_names = F)

colnames(metrics_omega91) <- c("tau", "N", "<x>", "epsilon")
colnames(metrics_omega92) <- c("tau", "N", "<x>", "epsilon")
colnames(metrics_omega93) <- c("tau", "N", "<x>", "epsilon")
colnames(metrics_omega94) <- c("tau", "N", "<x>", "epsilon")
colnames(metrics_omega95) <- c("tau", "N", "<x>", "epsilon")
```

```{r, fig.width=12, fig.height=5}
# n = 9
ggplot() +
  geom_line(data = metrics_omega91, aes(tau, epsilon, color = "omega=91")) +
  geom_line(data = metrics_omega92, aes(tau, epsilon, color = "omega=92")) +
  geom_line(data = metrics_omega93, aes(tau, epsilon, color = "omega=93")) +
  geom_line(data = metrics_omega94, aes(tau, epsilon, color = "omega=94")) +
  geom_line(data = metrics_omega95, aes(tau, epsilon, color = "omega=95")) +
  theme_light() +
  labs(y = TeX("$\\epsilon$"), x = TeX("$\\tau$")) +
  scale_color_discrete(labels = unname(TeX(c("$\\omega = 91$", "$\\omega = 92$", "$\\omega = 93$", "$\\omega = 94$", "$\\omega = 95$")))) +
  theme(legend.position = "top", 
        legend.title = element_blank(), legend.text = element_text(size = 13), 
        text = element_text(size = 14))
```

```{r, message=FALSE}
density.animation <- function(filename) {
  density <- read_csv(filename, col_names = F)
  
  rename <- function(x){
    if (x < 10) {
      return(name <- paste('000',i,'plot.png',sep=''))
    }
    if (x < 100 && i >= 10) {
      return(name <- paste('00',i,'plot.png', sep=''))
    }
    if (x >= 100) {
      return(name <- paste('0', i,'plot.png', sep=''))
    }
  }
  
  tmp <- str_split(filename, "/")[[1]][3]
  title_name <- str_split(tmp, "\\.")[[1]][1]
  cat(title_name, '\n')
  for (i in 1:nrow(density)) {
    name <- rename(i)
    png(name)
    plot(as.numeric(density[i,]), main = paste(title_name, i, sep = " "), xlab = "k", ylab = "rho", type = "l", lwd=2)
    dev.off()
  }
  
  convert_command <- paste('convert -delay 1x5 *.png -loop 0 ', title_name, ".gif", sep="")
  cat(convert_command)
  system(convert_command)
  system('rm *.png')
}
```


```{r}
density.animation("../output/density__n=1_kappa=8_omega=3.csv")
```


```{r, message=FALSE}
library(gridExtra)
# 100   # N
# 10    # tau
# 1e-4  # delta_tau
# 3     # kappa
# 1     # n - is changing
# 1000  # save_metrics
# 1000  # save_density

omega_n_4 <- read_csv("../output/resonance_freq_omega_n=4_energy_max.txt", col_names = F)
omega_n_9 <- read_csv("../output/resonance_freq_omega_n=9_energy_max.txt", col_names = F)
omega_n_1 <- read_csv("../output/resonance_freq_omega_n=1_energy_max.txt", col_names = F)

colnames(omega_n_1) <- c("omega", "Energy")
colnames(omega_n_4) <- c("omega", "Energy")
colnames(omega_n_9) <- c("omega", "Energy")
```

```{r, fig.width=14, fig.height=5}
o1 <- ggplot(omega_n_1) + 
  geom_line(aes(omega, Energy)) + 
  geom_vline(xintercept = 3 * pi * pi / 2, color = "red") + 
  geom_vline(xintercept = 4 * pi * pi / 2, color = "green") + 
  geom_vline(xintercept = 8 * pi * pi / 2, color = "blue") + 
  theme_light() +
  labs(title = "n=1", y = "<Energy>")
o4 <- ggplot(omega_n_4) + 
  geom_line(aes(omega, Energy)) + 
  geom_vline(xintercept = 3 * pi * pi / 2, color = "red") + 
  geom_vline(xintercept = 4 * pi * pi / 2, color = "green") + 
  geom_vline(xintercept = 8 * pi * pi / 2, color = "blue") + 
  theme_light() +
  labs(title = "n=4", y = "<Energy>")
o9 <- ggplot(omega_n_9) + 
  geom_line(aes(omega, Energy)) + 
  geom_vline(xintercept = 3 * pi * pi / 2, color = "red") + 
  geom_vline(xintercept = 4 * pi * pi / 2, color = "green") + 
  geom_vline(xintercept = 8 * pi * pi / 2, color = "blue") + 
  theme_light() +
  labs(title = "n=9", y = "<Energy>")

grid.arrange(o1, o4, o9, ncol = 3)
```


### Proper graph with resonanse omega
```{r, message=FALSE}
omega_n1 <- read_csv("../output/resonance_freq_omega_n=1_zoom_v1.txt", col_names = F)

colnames(omega_n1) <- c("omega", "Energy")

resonanse_omega <- omega_n1[which(omega_n1$Energy == max(omega_n1$Energy)), ]$omega
omega_n1$omega <- omega_n1$omega / resonanse_omega
```


```{r}
ggplot(omega_n1) + 
  geom_line(aes(omega, Energy)) + 
  theme_light() +
  labs(title = TeX("n=1, $\\omega_{res} = 14,7$"), y = TeX ("$< \\epsilon >$"), x = TeX("$\\omega / \\omega_{res}$")) +
  theme(text = element_text(size = 14))
```

### Animation - n=1->2, n=4->3 
```{r, message=F}
density.animation("../output/resonance_density_kappa=3__omega=14_n=1.csv")
density.animation("../output/resonance_density_kappa=3__omega=15_n=1.csv")
density.animation("../output/resonance_density_kappa=3__omega=16_n=1.csv")
```

```{r}
density.animation("../output/resonance_density_kappa=3__omega=33_n=4.csv")
density.animation("../output/resonance_density_kappa=3__omega=34_n=4.csv")
density.animation("../output/resonance_density_kappa=3__omega=35_n=4.csv")
```

```{r}
density.animation("../output/resonance_density_kappa=3__omega=95_n=9.csv")
density.animation("../output/resonance_density_kappa=3__omega=94_n=9.csv")
density.animation("../output/resonance_density_kappa=3__omega=93_n=9.csv")
```

```{r}
library(grid)
```


***
```{r, message=F}
omega_n_1_k_1 <- read_csv("../output/new_resonanse/kappa_1_omega_1_n_1.txt", col_names = F)
omega_n_1_k_3 <- read_csv("../output/new_resonanse/kappa_3_omega_1_n_1.txt", col_names = F)
omega_n_1_k_5 <- read_csv("../output/new_resonanse/kappa_5_omega_1_n_1.txt", col_names = F)
omega_n_1_k_7 <- read_csv("../output/new_resonanse/kappa_7_omega_1_n_1.txt", col_names = F)
omega_n_1_k_9 <- read_csv("../output/new_resonanse/kappa_9_omega_1_n_1.txt", col_names = F)


colnames(omega_n_1_k_1) <- c("omega", "Energy")
colnames(omega_n_1_k_3) <- c("omega", "Energy")
colnames(omega_n_1_k_5) <- c("omega", "Energy")
colnames(omega_n_1_k_7) <- c("omega", "Energy")
colnames(omega_n_1_k_9) <- c("omega", "Energy")
```

```{r}
library(grid)
```

```{r, fig.width=6, fig.height=4}
# pdf("plots/resonanse_n_1.pdf", width = 6, height = 4, paper = 'special')
o1 <- ggplot() + 
  geom_line(data = omega_n_1_k_1, aes(omega, Energy, color = "k=1")) + 
  geom_line(data = omega_n_1_k_3, aes(omega, Energy, color = "k=3")) + 
  geom_line(data = omega_n_1_k_5, aes(omega, Energy, color = "k=5")) + 
  geom_line(data = omega_n_1_k_7, aes(omega, Energy, color = "k=7")) + 
  geom_line(data = omega_n_1_k_9, aes(omega, Energy, color = "k=9")) + 
  geom_vline(xintercept = 3 * pi * pi / 2, color = "red") + 
  geom_vline(xintercept = 4 * pi * pi / 2, color = "green") + 
  geom_vline(xintercept = 8 * pi * pi / 2, color = "blue") + 
  # annotate("text", x=13, y=30, label = TeX("$3 \\pi^2 / 2$"), parse = TRUE) +
  theme_light() +
  labs(title = "n = 1", y = TeX("$< \\epsilon >_{max}$"), x = TeX("$\\omega$")) +
  scale_color_discrete(labels = unname(TeX(c("$\\kappa = 1$", "$\\kappa = 3$", "$\\kappa = 5$", "$\\kappa = 7$", "$\\kappa = 9$")))) +
  theme(legend.position = "bottom", 
        legend.title = element_blank(), legend.text = element_text(size = 13), 
        text = element_text(size = 14))
o1
grid.text(TeX("$3 \\pi^2 / 2$"), x = 0.31, y = 0.96)
grid.text(TeX("$4 \\pi^2 / 2$"), x = 0.41, y = 0.96)
grid.text(TeX("$8 \\pi^2 / 2$"), x = 0.76, y = 0.96)
dev.off()
```

```{r, message=F}
omega_n_4_k_1 <- read_csv("../output/new_resonanse/kappa_1_omega_1_n_4.txt", col_names = F)
omega_n_4_k_3 <- read_csv("../output/new_resonanse/kappa_3_omega_1_n_4.txt", col_names = F)
omega_n_4_k_5 <- read_csv("../output/new_resonanse/kappa_5_omega_1_n_4.txt", col_names = F)
omega_n_4_k_7 <- read_csv("../output/new_resonanse/kappa_7_omega_1_n_4.txt", col_names = F)
omega_n_4_k_9 <- read_csv("../output/new_resonanse/kappa_9_omega_1_n_4.txt", col_names = F)


colnames(omega_n_4_k_1) <- c("omega", "Energy")
colnames(omega_n_4_k_3) <- c("omega", "Energy")
colnames(omega_n_4_k_5) <- c("omega", "Energy")
colnames(omega_n_4_k_7) <- c("omega", "Energy")
colnames(omega_n_4_k_9) <- c("omega", "Energy")
```

```{r, fig.width=6, fig.height=4}
# pdf("plots/resonanse_n_4.pdf", width = 6, height = 4, paper = 'special')
o1 <- ggplot() + 
  geom_line(data = omega_n_4_k_1, aes(omega, Energy, color = "n=4,k=1")) + 
  geom_line(data = omega_n_4_k_3, aes(omega, Energy, color = "n=4,k=3")) + 
  geom_line(data = omega_n_4_k_5, aes(omega, Energy, color = "n=4,k=5")) + 
  geom_line(data = omega_n_4_k_7, aes(omega, Energy, color = "n=4,k=7")) + 
  geom_line(data = omega_n_4_k_9, aes(omega, Energy, color = "n=4,k=9")) + 
  geom_vline(xintercept = 3 * pi * pi / 2, color = "red") + 
  geom_vline(xintercept = 4 * pi * pi / 2, color = "green") + 
  geom_vline(xintercept = 8 * pi * pi / 2, color = "blue") + 
  theme_light() +
  labs(title = "n = 4", y = TeX("$< \\epsilon >_{max}$"), x = TeX("$\\omega$")) +
  scale_color_discrete(labels = unname(TeX(c("$\\kappa = 1$", "$\\kappa = 3$", "$\\kappa = 5$", "$\\kappa = 7$", "$\\kappa = 9$")))) +
  theme(legend.position = "bottom", 
        legend.title = element_blank(), legend.text = element_text(size = 13), 
        text = element_text(size = 14))
o1
grid.text(TeX("$3 \\pi^2 / 2$"), x = 0.32, y = 0.96)
grid.text(TeX("$4 \\pi^2 / 2$"), x = 0.42, y = 0.96)
grid.text(TeX("$8 \\pi^2 / 2$"), x = 0.76, y = 0.96)
# dev.off()
```

```{r, message=F}
omega_n_9_k_1 <- read_csv("../output/new_resonanse/kappa_1_omega_1_n_9.txt", col_names = F)
omega_n_9_k_3 <- read_csv("../output/new_resonanse/kappa_3_omega_1_n_9.txt", col_names = F)
omega_n_9_k_5 <- read_csv("../output/new_resonanse/kappa_5_omega_1_n_9.txt", col_names = F)
omega_n_9_k_7 <- read_csv("../output/new_resonanse/kappa_7_omega_1_n_9.txt", col_names = F)
omega_n_9_k_9 <- read_csv("../output/new_resonanse/kappa_9_omega_1_n_9.txt", col_names = F)

colnames(omega_n_9_k_1) <- c("omega", "Energy")
colnames(omega_n_9_k_3) <- c("omega", "Energy")
colnames(omega_n_9_k_5) <- c("omega", "Energy")
colnames(omega_n_9_k_7) <- c("omega", "Energy")
colnames(omega_n_9_k_9) <- c("omega", "Energy")
```

```{r, fig.width=6, fig.height=4}
# pdf("plots/resonanse_n_9.pdf", width = 6, height = 4, paper = 'special')
o1 <- ggplot() + 
  geom_line(data = omega_n_9_k_1, aes(omega, Energy, color = "n=9,k=1")) + 
  geom_line(data = omega_n_9_k_3, aes(omega, Energy, color = "n=9,k=3")) + 
  geom_line(data = omega_n_9_k_5, aes(omega, Energy, color = "n=9,k=5")) + 
  geom_line(data = omega_n_9_k_7, aes(omega, Energy, color = "n=9,k=7")) + 
  geom_line(data = omega_n_9_k_9, aes(omega, Energy, color = "n=9,k=9")) + 
  geom_vline(xintercept = 3 * pi * pi / 2, color = "red") + 
  geom_vline(xintercept = 4 * pi * pi / 2, color = "green") + 
  geom_vline(xintercept = 8 * pi * pi / 2, color = "blue") + 
  theme_light() +
  labs(title = "n = 9", y = TeX("$< \\epsilon >_{max}$"), x = TeX("$\\omega$")) +
  scale_color_discrete(labels = unname(TeX(c("$\\kappa = 1$", "$\\kappa = 3$", "$\\kappa = 5$", "$\\kappa = 7$", "$\\kappa = 9$")))) +
  theme(legend.position = "bottom", 
        legend.title = element_blank(), legend.text = element_text(size = 13), 
        text = element_text(size = 14))

o1
grid.text(TeX("$3 \\pi^2 / 2$"), x = 0.34, y = 0.96)
grid.text(TeX("$4 \\pi^2 / 2$"), x = 0.44, y = 0.96)
grid.text(TeX("$8 \\pi^2 / 2$"), x = 0.76, y = 0.96)
# dev.off()
```


```{r, message=FALSE}
omega_k_1 <- read_csv("../output/new_resonanse/kappa_1_omega_1_n_1_zoom.txt", col_names = F)
omega_k_3 <- read_csv("../output/new_resonanse/kappa_3_omega_1_n_1_zoom.txt", col_names = F)
omega_k_5 <- read_csv("../output/new_resonanse/kappa_5_omega_1_n_1_zoom.txt", col_names = F)
omega_k_7 <- read_csv("../output/new_resonanse/kappa_7_omega_1_n_1_zoom.txt", col_names = F)
omega_k_9 <- read_csv("../output/new_resonanse/kappa_9_omega_1_n_1_zoom.txt", col_names = F)

colnames(omega_k_1) <- c("omega", "Energy")
colnames(omega_k_3) <- c("omega", "Energy")
colnames(omega_k_5) <- c("omega", "Energy")
colnames(omega_k_7) <- c("omega", "Energy")
colnames(omega_k_9) <- c("omega", "Energy")

n <- nrow(omega_k_1) - 6
omega_k_1 <- omega_k_1[1:n, ]
omega_k_3 <- omega_k_3[1:n, ]
omega_k_5 <- omega_k_5[1:n, ]
omega_k_7 <- omega_k_7[1:n, ]
omega_k_9 <- omega_k_9[1:n, ]
```

```{r}
resonanse_omega <- omega_k_1[which(omega_k_1$Energy == max(omega_k_1$Energy)), ]$omega
omega_k_1$omega <- omega_k_1$omega / resonanse_omega
omega_k_3$omega <- omega_k_3$omega / resonanse_omega
omega_k_5$omega <- omega_k_5$omega / resonanse_omega
omega_k_7$omega <- omega_k_7$omega / resonanse_omega
omega_k_9$omega <- omega_k_9$omega / resonanse_omega
```


```{r}
# pdf("plots/resonanse_n_1_zoom.pdf", width = 6, height = 4, paper = 'special')
o1 <- ggplot() + 
  geom_line(data = omega_k_1, aes(omega, Energy, color = "k=1")) + 
  geom_line(data = omega_k_3, aes(omega, Energy, color = "k=3")) + 
  geom_line(data = omega_k_5, aes(omega, Energy, color = "k=5")) + 
  geom_line(data = omega_k_7, aes(omega, Energy, color = "k=7")) + 
  geom_line(data = omega_k_9, aes(omega, Energy, color = "k=9")) + 
  geom_vline(xintercept = 1, color = "red") + 
  theme_light() +
  labs(title = "n = 1", y = TeX("$< \\epsilon >_{max}$"), x = TeX("$\\omega / \\omega_{res}$")) +
  scale_color_discrete(labels = unname(TeX(c("$\\kappa = 1$", "$\\kappa = 3$", "$\\kappa = 5$", "$\\kappa = 7$", "$\\kappa = 9$")))) +
  theme(legend.position = "bottom", 
        legend.title = element_blank(), legend.text = element_text(size = 13), 
        text = element_text(size = 14))
o1
# dev.off()
```


** Energia, norma i położenie średnie dla omega rezonansowe **
```{r, info=F, message=F}
metrics_k1 <- read_csv("../output/metrics_resonance_kappa=1_omega=14.8_n=1.csv", col_names = F)
metrics_k3 <- read_csv("../output/metrics_resonance_kappa=3_omega=14.8_n=1.csv", col_names = F)
metrics_k5 <- read_csv("../output/metrics_resonance_kappa=5_omega=14.8_n=1.csv", col_names = F)
metrics_k7 <- read_csv("../output/metrics_resonance_kappa=7_omega=14.8_n=1.csv", col_names = F)
metrics_k9 <- read_csv("../output/metrics_resonance_kappa=9_omega=14.8_n=1.csv", col_names = F)

colnames(metrics_k1) <- c("tau", "N", "<x>", "epsilon")
colnames(metrics_k3) <- c("tau", "N", "<x>", "epsilon")
colnames(metrics_k5) <- c("tau", "N", "<x>", "epsilon")
colnames(metrics_k7) <- c("tau", "N", "<x>", "epsilon")
colnames(metrics_k9) <- c("tau", "N", "<x>", "epsilon")
```

# TODO - dodać te 3 wykresy do raportu !!
```{r, fig.width=6, fig.height=4}
ggplot() +
  geom_line(data = metrics_k1, aes(tau, epsilon, color = "k=1")) +
  geom_line(data = metrics_k3, aes(tau, epsilon, color = "k=3")) +
  geom_line(data = metrics_k5, aes(tau, epsilon, color = "k=5")) +
  geom_line(data = metrics_k7, aes(tau, epsilon, color = "k=7")) +
  geom_line(data = metrics_k9, aes(tau, epsilon, color = "k=9")) +
  theme_light() +
  labs(y = TeX("$\\epsilon$"), x = TeX("$\\tau$")) +
  scale_color_discrete(labels = unname(TeX(c("$\\kappa = 1$", "$\\kappa = 3$", "$\\kappa = 5$", "$\\kappa = 7$", "$\\kappa = 9$")))) +
  theme(legend.position = "top", 
        legend.title = element_blank(), legend.text = element_text(size = 13), 
        text = element_text(size = 14))
```

```{r, fig.width=6, fig.height=4}
ggplot() +
  geom_line(data = metrics_k1, aes(tau, `<x>`, color = "k=1")) +
  geom_line(data = metrics_k3, aes(tau, `<x>`, color = "k=3")) +
  geom_line(data = metrics_k5, aes(tau, `<x>`, color = "k=5")) +
  geom_line(data = metrics_k7, aes(tau, `<x>`, color = "k=7")) +
  geom_line(data = metrics_k9, aes(tau, `<x>`, color = "k=9")) +
  theme_light() +
  labs(y = TeX("$<x>$"), x = TeX("$\\tau$")) +
  scale_color_discrete(labels = unname(TeX(c("$\\kappa = 1$", "$\\kappa = 3$", "$\\kappa = 5$", "$\\kappa = 7$", "$\\kappa = 9$")))) +
  theme(legend.position = "top", 
        legend.title = element_blank(), legend.text = element_text(size = 13), 
        text = element_text(size = 14))
```

```{r, fig.width=6, fig.height=4}
ggplot() +
  geom_line(data = metrics_k1, aes(tau, N, color = "k=1")) +
  geom_line(data = metrics_k3, aes(tau, N, color = "k=3")) +
  geom_line(data = metrics_k5, aes(tau, N, color = "k=5")) +
  geom_line(data = metrics_k7, aes(tau, N, color = "k=7")) +
  geom_line(data = metrics_k9, aes(tau, N, color = "k=9")) +
  theme_light() +
  labs(y = TeX("$N$"), x = TeX("$\\tau$")) +
  scale_color_discrete(labels = unname(TeX(c("$\\kappa = 1$", "$\\kappa = 3$", "$\\kappa = 5$", "$\\kappa = 7$", "$\\kappa = 9$")))) +
  theme(legend.position = "top", 
        legend.title = element_blank(), legend.text = element_text(size = 13), 
        text = element_text(size = 14))
```
